#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:demo;mode=MYSQL
#    username: username
#    password: password
#  sql:
#    init:
#      schema-locations:
#        - classpath:db/schema-simple_demo.sql
#      data-locations:
#        - classpath:db/data-simple_demo.sql

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimeZone=UTC
    username: bdtd
    password: Mima!@2202
    driver-class-name: com.mysql.cj.jdbc.Driver