// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Demo.proto

// Protobuf Java Version: 3.25.3
package org.oizehsgl.javaLearning.springbootdemo.model.dto;

public final class DemoProtobufDto {
  private DemoProtobufDto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DemoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Demo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *简单属性
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <pre>
     * list示例
     * </pre>
     *
     * <code>repeated .PhoneNumber phone = 5;</code>
     */
    java.util.List<org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber> 
        getPhoneList();
    /**
     * <pre>
     * list示例
     * </pre>
     *
     * <code>repeated .PhoneNumber phone = 5;</code>
     */
    org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber getPhone(int index);
    /**
     * <pre>
     * list示例
     * </pre>
     *
     * <code>repeated .PhoneNumber phone = 5;</code>
     */
    int getPhoneCount();
    /**
     * <pre>
     * list示例
     * </pre>
     *
     * <code>repeated .PhoneNumber phone = 5;</code>
     */
    java.util.List<? extends org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumberOrBuilder> 
        getPhoneOrBuilderList();
    /**
     * <pre>
     * list示例
     * </pre>
     *
     * <code>repeated .PhoneNumber phone = 5;</code>
     */
    org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumberOrBuilder getPhoneOrBuilder(
        int index);

    /**
     * <code>.Demo.Map map = 6;</code>
     * @return Whether the map field is set.
     */
    boolean hasMap();
    /**
     * <code>.Demo.Map map = 6;</code>
     * @return The map.
     */
    org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map getMap();
    /**
     * <code>.Demo.Map map = 6;</code>
     */
    org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.MapOrBuilder getMapOrBuilder();
  }
  /**
   * Protobuf type {@code Demo}
   */
  public static final class Demo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Demo)
      DemoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Demo.newBuilder() to construct.
    private Demo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Demo() {
      name_ = "";
      email_ = "";
      phone_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Demo();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.internal_static_Demo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.internal_static_Demo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.class, org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Builder.class);
    }

    public interface MapOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Demo.Map)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      java.lang.String getKey();
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      /**
       * <code>int32 value = 2;</code>
       * @return The value.
       */
      int getValue();
    }
    /**
     * <pre>
     * map示例
     * </pre>
     *
     * Protobuf type {@code Demo.Map}
     */
    public static final class Map extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Demo.Map)
        MapOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Map.newBuilder() to construct.
      private Map(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Map() {
        key_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Map();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.internal_static_Demo_Map_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.internal_static_Demo_Map_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.class, org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.Builder.class);
      }

      public static final int KEY_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      @java.lang.Override
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private int value_ = 0;
      /**
       * <code>int32 value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public int getValue() {
        return value_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
        }
        if (value_ != 0) {
          output.writeInt32(2, value_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
        }
        if (value_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, value_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map)) {
          return super.equals(obj);
        }
        org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map other = (org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map) obj;

        if (!getKey()
            .equals(other.getKey())) return false;
        if (getValue()
            != other.getValue()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * map示例
       * </pre>
       *
       * Protobuf type {@code Demo.Map}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Demo.Map)
          org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.MapOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.internal_static_Demo_Map_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.internal_static_Demo_Map_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.class, org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.Builder.class);
        }

        // Construct using org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          key_ = "";
          value_ = 0;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.internal_static_Demo_Map_descriptor;
        }

        @java.lang.Override
        public org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map getDefaultInstanceForType() {
          return org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.getDefaultInstance();
        }

        @java.lang.Override
        public org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map build() {
          org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map buildPartial() {
          org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map result = new org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.key_ = key_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.value_ = value_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map) {
            return mergeFrom((org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map other) {
          if (other == org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.getDefaultInstance()) return this;
          if (!other.getKey().isEmpty()) {
            key_ = other.key_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (other.getValue() != 0) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  key_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 16: {
                  value_ = input.readInt32();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 16
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object key_ = "";
        /**
         * <code>string key = 1;</code>
         * @return The key.
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string key = 1;</code>
         * @return The bytes for key.
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string key = 1;</code>
         * @param value The key to set.
         * @return This builder for chaining.
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          key_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string key = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearKey() {
          key_ = getDefaultInstance().getKey();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string key = 1;</code>
         * @param value The bytes for key to set.
         * @return This builder for chaining.
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          key_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private int value_ ;
        /**
         * <code>int32 value = 2;</code>
         * @return The value.
         */
        @java.lang.Override
        public int getValue() {
          return value_;
        }
        /**
         * <code>int32 value = 2;</code>
         * @param value The value to set.
         * @return This builder for chaining.
         */
        public Builder setValue(int value) {

          value_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>int32 value = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Demo.Map)
      }

      // @@protoc_insertion_point(class_scope:Demo.Map)
      private static final org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map();
      }

      public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Map>
          PARSER = new com.google.protobuf.AbstractParser<Map>() {
        @java.lang.Override
        public Map parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Map> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Map> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <pre>
     *简单属性
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_ = 0;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object email_ = "";
    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private java.util.List<org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber> phone_;
    /**
     * <pre>
     * list示例
     * </pre>
     *
     * <code>repeated .PhoneNumber phone = 5;</code>
     */
    @java.lang.Override
    public java.util.List<org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber> getPhoneList() {
      return phone_;
    }
    /**
     * <pre>
     * list示例
     * </pre>
     *
     * <code>repeated .PhoneNumber phone = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumberOrBuilder> 
        getPhoneOrBuilderList() {
      return phone_;
    }
    /**
     * <pre>
     * list示例
     * </pre>
     *
     * <code>repeated .PhoneNumber phone = 5;</code>
     */
    @java.lang.Override
    public int getPhoneCount() {
      return phone_.size();
    }
    /**
     * <pre>
     * list示例
     * </pre>
     *
     * <code>repeated .PhoneNumber phone = 5;</code>
     */
    @java.lang.Override
    public org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber getPhone(int index) {
      return phone_.get(index);
    }
    /**
     * <pre>
     * list示例
     * </pre>
     *
     * <code>repeated .PhoneNumber phone = 5;</code>
     */
    @java.lang.Override
    public org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumberOrBuilder getPhoneOrBuilder(
        int index) {
      return phone_.get(index);
    }

    public static final int MAP_FIELD_NUMBER = 6;
    private org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map map_;
    /**
     * <code>.Demo.Map map = 6;</code>
     * @return Whether the map field is set.
     */
    @java.lang.Override
    public boolean hasMap() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Demo.Map map = 6;</code>
     * @return The map.
     */
    @java.lang.Override
    public org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map getMap() {
      return map_ == null ? org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.getDefaultInstance() : map_;
    }
    /**
     * <code>.Demo.Map map = 6;</code>
     */
    @java.lang.Override
    public org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.MapOrBuilder getMapOrBuilder() {
      return map_ == null ? org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.getDefaultInstance() : map_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
      }
      for (int i = 0; i < phone_.size(); i++) {
        output.writeMessage(5, phone_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(6, getMap());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
      }
      for (int i = 0; i < phone_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, phone_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getMap());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo)) {
        return super.equals(obj);
      }
      org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo other = (org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo) obj;

      if (getId()
          != other.getId()) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getPhoneList()
          .equals(other.getPhoneList())) return false;
      if (hasMap() != other.hasMap()) return false;
      if (hasMap()) {
        if (!getMap()
            .equals(other.getMap())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (getPhoneCount() > 0) {
        hash = (37 * hash) + PHONE_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneList().hashCode();
      }
      if (hasMap()) {
        hash = (37 * hash) + MAP_FIELD_NUMBER;
        hash = (53 * hash) + getMap().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Demo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Demo)
        org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.DemoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.internal_static_Demo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.internal_static_Demo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.class, org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Builder.class);
      }

      // Construct using org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPhoneFieldBuilder();
          getMapFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        age_ = 0;
        name_ = "";
        email_ = "";
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
        } else {
          phone_ = null;
          phoneBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        map_ = null;
        if (mapBuilder_ != null) {
          mapBuilder_.dispose();
          mapBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.internal_static_Demo_descriptor;
      }

      @java.lang.Override
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo getDefaultInstanceForType() {
        return org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.getDefaultInstance();
      }

      @java.lang.Override
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo build() {
        org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo buildPartial() {
        org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo result = new org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo result) {
        if (phoneBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            phone_ = java.util.Collections.unmodifiableList(phone_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.phone_ = phone_;
        } else {
          result.phone_ = phoneBuilder_.build();
        }
      }

      private void buildPartial0(org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.email_ = email_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.map_ = mapBuilder_ == null
              ? map_
              : mapBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo) {
          return mergeFrom((org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo other) {
        if (other == org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (phoneBuilder_ == null) {
          if (!other.phone_.isEmpty()) {
            if (phone_.isEmpty()) {
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensurePhoneIsMutable();
              phone_.addAll(other.phone_);
            }
            onChanged();
          }
        } else {
          if (!other.phone_.isEmpty()) {
            if (phoneBuilder_.isEmpty()) {
              phoneBuilder_.dispose();
              phoneBuilder_ = null;
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000010);
              phoneBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPhoneFieldBuilder() : null;
            } else {
              phoneBuilder_.addAllMessages(other.phone_);
            }
          }
        }
        if (other.hasMap()) {
          mergeMap(other.getMap());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                age_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber m =
                    input.readMessage(
                        org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.parser(),
                        extensionRegistry);
                if (phoneBuilder_ == null) {
                  ensurePhoneIsMutable();
                  phone_.add(m);
                } else {
                  phoneBuilder_.addMessage(m);
                }
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getMapFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       *简单属性
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       *简单属性
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *简单属性
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {

        age_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 4;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.util.List<org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber> phone_ =
        java.util.Collections.emptyList();
      private void ensurePhoneIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          phone_ = new java.util.ArrayList<org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber>(phone_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber, org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.Builder, org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumberOrBuilder> phoneBuilder_;

      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public java.util.List<org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber> getPhoneList() {
        if (phoneBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phone_);
        } else {
          return phoneBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public int getPhoneCount() {
        if (phoneBuilder_ == null) {
          return phone_.size();
        } else {
          return phoneBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber getPhone(int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);
        } else {
          return phoneBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public Builder setPhone(
          int index, org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.set(index, value);
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public Builder setPhone(
          int index, org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.set(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public Builder addPhone(org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public Builder addPhone(
          int index, org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(index, value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public Builder addPhone(
          org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public Builder addPhone(
          int index, org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public Builder addAllPhone(
          java.lang.Iterable<? extends org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber> values) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, phone_);
          onChanged();
        } else {
          phoneBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public Builder clearPhone() {
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public Builder removePhone(int index) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.remove(index);
          onChanged();
        } else {
          phoneBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.Builder getPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumberOrBuilder getPhoneOrBuilder(
          int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);  } else {
          return phoneBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public java.util.List<? extends org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumberOrBuilder> 
           getPhoneOrBuilderList() {
        if (phoneBuilder_ != null) {
          return phoneBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phone_);
        }
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.Builder addPhoneBuilder() {
        return getPhoneFieldBuilder().addBuilder(
            org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.getDefaultInstance());
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.Builder addPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().addBuilder(
            index, org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.getDefaultInstance());
      }
      /**
       * <pre>
       * list示例
       * </pre>
       *
       * <code>repeated .PhoneNumber phone = 5;</code>
       */
      public java.util.List<org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.Builder> 
           getPhoneBuilderList() {
        return getPhoneFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber, org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.Builder, org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumberOrBuilder> 
          getPhoneFieldBuilder() {
        if (phoneBuilder_ == null) {
          phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber, org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.Builder, org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumberOrBuilder>(
                  phone_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          phone_ = null;
        }
        return phoneBuilder_;
      }

      private org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map map_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map, org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.Builder, org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.MapOrBuilder> mapBuilder_;
      /**
       * <code>.Demo.Map map = 6;</code>
       * @return Whether the map field is set.
       */
      public boolean hasMap() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>.Demo.Map map = 6;</code>
       * @return The map.
       */
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map getMap() {
        if (mapBuilder_ == null) {
          return map_ == null ? org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.getDefaultInstance() : map_;
        } else {
          return mapBuilder_.getMessage();
        }
      }
      /**
       * <code>.Demo.Map map = 6;</code>
       */
      public Builder setMap(org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map value) {
        if (mapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          map_ = value;
        } else {
          mapBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.Demo.Map map = 6;</code>
       */
      public Builder setMap(
          org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.Builder builderForValue) {
        if (mapBuilder_ == null) {
          map_ = builderForValue.build();
        } else {
          mapBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.Demo.Map map = 6;</code>
       */
      public Builder mergeMap(org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map value) {
        if (mapBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
            map_ != null &&
            map_ != org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.getDefaultInstance()) {
            getMapBuilder().mergeFrom(value);
          } else {
            map_ = value;
          }
        } else {
          mapBuilder_.mergeFrom(value);
        }
        if (map_ != null) {
          bitField0_ |= 0x00000020;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.Demo.Map map = 6;</code>
       */
      public Builder clearMap() {
        bitField0_ = (bitField0_ & ~0x00000020);
        map_ = null;
        if (mapBuilder_ != null) {
          mapBuilder_.dispose();
          mapBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.Demo.Map map = 6;</code>
       */
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.Builder getMapBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getMapFieldBuilder().getBuilder();
      }
      /**
       * <code>.Demo.Map map = 6;</code>
       */
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.MapOrBuilder getMapOrBuilder() {
        if (mapBuilder_ != null) {
          return mapBuilder_.getMessageOrBuilder();
        } else {
          return map_ == null ?
              org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.getDefaultInstance() : map_;
        }
      }
      /**
       * <code>.Demo.Map map = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map, org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.Builder, org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.MapOrBuilder> 
          getMapFieldBuilder() {
        if (mapBuilder_ == null) {
          mapBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map, org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.Map.Builder, org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo.MapOrBuilder>(
                  getMap(),
                  getParentForChildren(),
                  isClean());
          map_ = null;
        }
        return mapBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Demo)
    }

    // @@protoc_insertion_point(class_scope:Demo)
    private static final org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo();
    }

    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Demo>
        PARSER = new com.google.protobuf.AbstractParser<Demo>() {
      @java.lang.Override
      public Demo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Demo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Demo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.oizehsgl.javaLearning.springbootdemo.model.dto.DemoProtobufDto.Demo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Demo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Demo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Demo_Map_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Demo_Map_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nDemo.proto\032\021PhoneNumber.proto\"\224\001\n\004Demo" +
      "\022\n\n\002id\030\001 \001(\005\022\013\n\003age\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022" +
      "\r\n\005email\030\004 \001(\t\022\033\n\005phone\030\005 \003(\0132\014.PhoneNum" +
      "ber\022\026\n\003map\030\006 \001(\0132\t.Demo.Map\032!\n\003Map\022\013\n\003ke" +
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\005BE\n2org.oizehsgl.j" +
      "avaLearning.springbootdemo.model.dtoB\017De" +
      "moProtobufDtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.getDescriptor(),
        });
    internal_static_Demo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Demo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Demo_descriptor,
        new java.lang.String[] { "Id", "Age", "Name", "Email", "Phone", "Map", });
    internal_static_Demo_Map_descriptor =
      internal_static_Demo_descriptor.getNestedTypes().get(0);
    internal_static_Demo_Map_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Demo_Map_descriptor,
        new java.lang.String[] { "Key", "Value", });
    org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
