// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PhoneNumber.proto

// Protobuf Java Version: 3.25.3
package org.oizehsgl.javaLearning.springbootdemo.model.dto;

public final class PhoneNumberProtobufDto {
  private PhoneNumberProtobufDto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PhoneNumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PhoneNumber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string number = 1;</code>
     * @return The number.
     */
    java.lang.String getNumber();
    /**
     * <code>string number = 1;</code>
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <code>.PhoneNumber.PhoneType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.PhoneNumber.PhoneType type = 2;</code>
     * @return The type.
     */
    org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.PhoneType getType();
  }
  /**
   * Protobuf type {@code PhoneNumber}
   */
  public static final class PhoneNumber extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PhoneNumber)
      PhoneNumberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PhoneNumber.newBuilder() to construct.
    private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PhoneNumber() {
      number_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PhoneNumber();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.internal_static_PhoneNumber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.internal_static_PhoneNumber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.class, org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.Builder.class);
    }

    /**
     * <pre>
     * 枚举示例
     * </pre>
     *
     * Protobuf enum {@code PhoneNumber.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0),
      /**
       * <code>TELEPHONE = 1;</code>
       */
      TELEPHONE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>TELEPHONE = 1;</code>
       */
      public static final int TELEPHONE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PhoneType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static PhoneType forNumber(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return TELEPHONE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhoneType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PhoneType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:PhoneNumber.PhoneType)
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object number_ = "";
    /**
     * <code>string number = 1;</code>
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <code>string number = 1;</code>
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_ = 0;
    /**
     * <code>.PhoneNumber.PhoneType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.PhoneNumber.PhoneType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.PhoneType getType() {
      org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.PhoneType result = org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.PhoneType.forNumber(type_);
      return result == null ? org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.PhoneType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
      }
      if (type_ != org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.PhoneType.MOBILE.getNumber()) {
        output.writeEnum(2, type_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
      }
      if (type_ != org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.PhoneType.MOBILE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber)) {
        return super.equals(obj);
      }
      org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber other = (org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber) obj;

      if (!getNumber()
          .equals(other.getNumber())) return false;
      if (type_ != other.type_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PhoneNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PhoneNumber)
        org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.internal_static_PhoneNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.internal_static_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.class, org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.Builder.class);
      }

      // Construct using org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        number_ = "";
        type_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.internal_static_PhoneNumber_descriptor;
      }

      @java.lang.Override
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber getDefaultInstanceForType() {
        return org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.getDefaultInstance();
      }

      @java.lang.Override
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber build() {
        org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber buildPartial() {
        org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber result = new org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.number_ = number_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.type_ = type_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber) {
          return mergeFrom((org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber other) {
        if (other == org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.getDefaultInstance()) return this;
        if (!other.getNumber().isEmpty()) {
          number_ = other.number_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                number_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object number_ = "";
      /**
       * <code>string number = 1;</code>
       * @return The number.
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       * @return The bytes for number.
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        number_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        number_ = getDefaultInstance().getNumber();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        number_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.PhoneNumber.PhoneType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.PhoneNumber.PhoneType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.PhoneNumber.PhoneType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.PhoneType getType() {
        org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.PhoneType result = org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.PhoneType.forNumber(type_);
        return result == null ? org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.PhoneType.UNRECOGNIZED : result;
      }
      /**
       * <code>.PhoneNumber.PhoneType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber.PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.PhoneNumber.PhoneType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PhoneNumber)
    }

    // @@protoc_insertion_point(class_scope:PhoneNumber)
    private static final org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber();
    }

    public static org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PhoneNumber>
        PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
      @java.lang.Override
      public PhoneNumber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PhoneNumber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.oizehsgl.javaLearning.springbootdemo.model.dto.PhoneNumberProtobufDto.PhoneNumber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PhoneNumber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PhoneNumber.proto\"k\n\013PhoneNumber\022\016\n\006nu" +
      "mber\030\001 \001(\t\022$\n\004type\030\002 \001(\0162\026.PhoneNumber.P" +
      "honeType\"&\n\tPhoneType\022\n\n\006MOBILE\020\000\022\r\n\tTEL" +
      "EPHONE\020\001BL\n2org.oizehsgl.javaLearning.sp" +
      "ringbootdemo.model.dtoB\026PhoneNumberProto" +
      "bufDtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PhoneNumber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
