spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
rabbitmq:
  direct:
    exchange:
      - directExchange1
      - directExchange2
    queue:
      - directQueue1
      - directQueue2
    routing-key:
      - directRoutingKey1
      - directRoutingKey2
