parameter:
  string-head: "head"
  string-tail: "${parameter.string-head}-tail"
  int-random: ${random.int(10)}
  int-array: 1,2,3
  str-array: 1,2,3
  string-list:
    - list1
    - list2
    - list3
  map:
    key1: value1
    key2: value2
    key3: value3
  map-list:
    - key: key1
      value: value1
    - key: key2
      value: value2
    - key: key3
      value: value3
  sub:
    integer: 1
    static-string: "static-string"