spring:
  #tomcat:
  #  accept-count: 100 # queue capacity
  #  max-connections: 8192 # tcp connection pool size
  #  keep-alive-timeout: 60s # keep alive
  #  connection-timeout: 60s # accept time out
  #  threads:
  #    min-spare: 10 # core size
  #    max: 200 # max size
  #task:
  #  scheduling:
  #    thread-name-prefix: schedule.yml-
  #    pool:
  #      size: 10
  #  execution:
  #    pool:
  #      # 核心线程数
  #      core-size: 8
  #      # 最大线程数
  #      max-size: 16
  #      # 空闲线程存活时间
  #      keep-alive: 60s
  #      # 是否允许核心线程超时
  #      allow-core-thread-timeout: true
  #      # 线程队列数量
  #      queue-capacity: 100
  #    shutdown:
  #      # 关闭等待
  #      await-termination: false
  #      await-termination-period:
  #    # 前缀名称
  #    thread-name-prefix: async.yml-