DROP TABLE IF EXISTS demo_data;

CREATE TABLE demo_data
(
	id BIGINT NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    deleted bit NOT NULL DEFAULT false COMMENT '删除',
	PRIMARY KEY (id)
);