mqtt:
  consumer:
    url: tcp://127.0.0.1:1884
    username: admin
    password: admin123
    qos: 1
    clientId: mqttConsumer
    topics: /defaultTopic
    timeout: 10
    keepAlive: 20
  producer:
    url: tcp://127.0.0.1:1884
    username: admin
    password: admin123
    qos: 1
    clientId: mqttProducer
    topics: /defaultTopic
    timeout: 10
    keepAlive: 20
